language: scala
dist: bionic
sudo: false
scala:
  - 2.11.12
  - 2.12.12
  - 2.13.2
cache:
  directories:
    - '$HOME/node_modules'
    - $HOME/.ivy2
services:
  - mongodb
jdk:
  - openjdk8
matrix:
  include:
  - scala: 2.12.12
    jdk: openjdk11
    env: DISABLE_PUBLISH=true
  - scala: 2.12.12
    jdk: openjdk12
    env: DISABLE_PUBLISH=true
  - scala: 2.13.2
    jdk: openjdk11
    env: DISABLE_PUBLISH=true
  - scala: 2.13.2
    jdk: openjdk12
    env: DISABLE_PUBLISH=true
script: ./travis.sh
branches:
  only:
    - master
    - /^release-branch-.*$/
    - /^wip-/

node_js:
  - "4.1"
before_script:
  - "cd web/webkit"
  - "npm install"
  - "cd -"
notifications:
  webhooks:
    urls: []
    on_success: always
    on_failure: always
    on_start: never
  email:
    recipients: []
    on_success: change
    on_failure: always
